### ISSUE TITLE
Message fails to send before bot is killed

### ISSUE THREAD

**Issue by CMDRMgram** [antixenoinitiative/warden.bot#11]
https://github.com/antixenoinitiative/warden.bot/blob/905fabda3d68bbe9d037597403f975f4b255df9e/commands/admin/kill.js#L7

**Comment by henrygrv** [comment]
the issue is that .destroy() is called before .send() 

i think .send is async and .destroy is sync ..  i will have a look at the documentation

**Comment by henrygrv** [comment]
fixed it

will be in pr
