### ISSUE TITLE
Add filtering to -members command

### ISSUE THREAD

**Issue by MgramTheDuck** [antixenoinitiative/warden.bot#14]
I would like to see if we can add some filters to this command. 

- newest/recent
- oldest

For example `-members recruit recent csv`

**Comment by henrygrv** [comment]
i'm afraid i don't think this is possible. the only way you could do it is by writing to a database every single time that [guildMemberUpdate](https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-guildMemberUpdate) is emitted. no data is stored in a guild object about when a role was given to a user.
