### ISSUE TITLE
/ranks "Other Ranks" fails.

### ISSUE THREAD

**Issue by testfax** [antixenoinitiative/warden.bot#173]
File Location:
- /commands/Warden/info/Ranks.js
- /config.json

Looking for a coder to assist in modifying ranks.js to attain dynamic state instead of a hardcoded state. It would greatly assist in making the bot better. I'm actively working on more items and trying to garner assistance.

When clicking on Other Ranks, the code is told to specifically look for ranks. It currently errors out due to a 'most likely condition' where the rank no longer exists.

All sections must be changed, however this is an example of a hardcoded embed. Must be changed to dynamic to allow future flexibility. Function should include the ability to omit a rank if it doesn't exist in the server to prevent blockage.

```js
.addFields(
 { name: "Annihilator", value: roleCache.get("528577192746287104").members.size.toString(), inline: true },
 { name: "Exterminator", value: roleCache.get("528577143844634644").members.size.toString(), inline: true },
 { name: "Defender", value: roleCache.get("528576199639957504").members.size.toString(), inline: true },
 { name: "Mentor", value: roleCache.get("468153018899234816").members.size.toString(), inline: true },
 { name: "Veteran", value: roleCache.get("811106163608780810").members.size.toString(), inline: true },
 { name: "Collector", value: roleCache.get("476049331405717504").members.size.toString(), inline: true },
 { name: "Party Champion", value: roleCache.get("638111509569863690").members.size.toString(), inline: true },
 { name: "Party Survivor", value: roleCache.get("417401084198387713").members.size.toString(), inline: true },
 { name: "Old Guard", value: roleCache.get("427304200737783810").members.size.toString(), inline: true },
 { name: "Lernaean Seeker", value: roleCache.get("484470882325233684").members.size.toString(), inline: true },
 { name: "Callous Fringe", value: roleCache.get("427826781752524800").members.size.toString(), inline: true },
 { name: "Xeno Unraveler", value: roleCache.get("537743539862503425").members.size.toString(), inline: true },
 { name: "Avower", value: roleCache.get("439500275280117760").members.size.toString(), inline: true },
 { name: "BGS Loyalist", value: roleCache.get("712110659814293586").members.size.toString(), inline: true },
 { name: "BGS Operator", value: roleCache.get("505888282484408340").members.size.toString(), inline: true },
 { name: "Conspirator", value: roleCache.get("800227831694229514").members.size.toString(), inline: true },
 { name: "Ambassador", value: roleCache.get("431671409375182849").members.size.toString(), inline: true },
 { name: "Jaeger", value: roleCache.get("638143561698639872").members.size.toString(), inline: true },
 { name: "Carrier Commander", value: roleCache.get("720206853350359121").members.size.toString(), inline: true },
 )
```
- This should have a list in config.json `Warden.ranksCommand` array.
- Basic example for config.json location. The specific rank names required to be filled in are in Ranks.js. 
```js
"ranksCommand": {
            "challenge_ranks": [],
            "competitive_ranks": [],
            "progression_ranks": [],
            "other_ranks": [
                "Annihilator",
                "Exterminator"
            ]
        },
```
- Retrieve a list of all ranks on server and use find() to get the id of the named rank.

This will allow future proof use of the command should Ranks change or get sent to the archive bin. Simply adding the correct name to the array will ensure the list is properly generated.

After the appropriate list is generated use a loop on the embed to add.
```js
for (let user of/in memberList ) { 
returnEmbed.addFields({ name: "", value: ""})
}

```
to add appropriate roles from `Warden.ranksCommand` array.

**Comment by Toscany** [comment]
Yup the multiple locations where ranks populations are hardcoded would suggest it would be nice to utilize a function instead
