### ISSUE TITLE
Need to update code to work with openai 4.x.x

### ISSUE THREAD

**Issue by Astyrrean** [antixenoinitiative/warden.bot#174]
Current code works with openai 3.3.0 library.

Upgrading to opeanai 4.x.x "breaks" the code, as the way to call that library changed in 4.x.x.

The workaround for now has been to force use of the 3.3.0 library.

At some point it would be great to update the code, and switch the library to current one.

**Comment by testfax** [comment]
Deprecated this feature. Required a chat GPT key and not necessarily personal info secure on the requestors part.
