### ISSUE TITLE
collapseSequence only handles two consecutive numbers.

### ISSUE THREAD

**Issue by MgramTheDuck** [antixenoinitiative/warden.bot#5]
Function to collapse a sequence of weeks does not collapse more than 2 consecutive weeks at a time.

https://github.com/antixenoinitiative/warden.bot/blob/3b104e45d51b08b2f24c64c7051b0811a0da828e/commands/incdata.js#L26

**Comment by CMDRMgram** [comment]
Issue exists here: https://github.com/antixenoinitiative/warden.bot/blob/3842bc8d118a5b8d9bb0d7b6da6ef9d4b36ef721/commands/inchistory.js#L26
